export const ActionType = [
  { key: 'ITEMACTION_DEL', value: '删除' },
  { key: 'ITEMACTION_ADD', value: '增加' }
]

export const ReasonType = [
  { key: 'ITEMLOG_SHOP', value: '商人购物' },
  { key: 'ITEMLOG_LOOT', value: '拾取' },
  { key: 'ITEMLOG_GM_COMMAND', value: 'GM指令' },
  { key: 'ITEMLOG_QUEST_PREPAY', value: '接受任务给予' },
  { key: 'ITEMLOG_QUEST_REWARD', value: '完成任务奖励' },
  { key: 'ITEMLOG_DUNGEON_REWARD', value: '副本奖励' },
  { key: 'ITEMLOG_PLAYER_STALL', value: '玩家摆摊' },
  { key: 'ITEMLOG_PLAYER_TRADE', value: '玩家交易' },
  { key: 'ITEMLOG_BUY_BACK', value: '回购' },
  { key: 'ITEMLOG_CREATE_ROLE', value: '创建角色' },
  { key: 'ITEMLOG_CREATE_HERO', value: '创建英雄' },
  { key: 'ITEMLOG_SCRIPT', value: '脚本' },
  { key: 'ITEMLOG_GET_MAIL_ATTACH', value: '邮件附件' },
  { key: 'ITEMLOG_GUILD_STORAGE', value: '公会仓库进出' },
  { key: 'ITEMLOG_GUILD_DESTORY', value: ' 公会解散' },
  { key: 'ITEMLOG_ACHIEVEMENT_REWARD', value: '成就奖励' },
  { key: 'ITEMLOG_UPGRADE_SOUL', value: '灵石升级' },
  { key: 'ITEMLOG_REMOVE_SOUL', value: '灵石拆除' },
  { key: 'ITEMLOG_NPC_DROP', value: '怪物掉落' },
  { key: 'ITEMLOG_USER_REQUEST', value: '玩家丢弃' },
  { key: 'ITEMLOG_SELL', value: '出售给商人' },
  { key: 'ITEMLOG_CAST_SPELL', value: '释放技能' },
  { key: 'ITEMLOG_REFINE_ITEM', value: '体格强化' },
  { key: 'ITEMLOG_COMPLETE_QUEST', value: '完成任务上交' },
  { key: 'ITEMLOG_CREATE_GUILD', value: '创建公会' },
  { key: 'ITEMLOG_USE_ITEM', value: '使用物品' },
  { key: 'ITEMLOG_INSERT_SOUL', value: '灵石融合' },
  { key: 'ITEMLOG_AUCTION_SELL', value: '拍卖行出售' },
  { key: 'ITEMLOG_RUNE', value: '铭文' },
  { key: 'ITEMLOG_DECOMPOSE', value: '物品分解' },
  { key: 'ITEMLOG_COMPOSE', value: '物品合成' },
  { key: 'ITEMLOG_ACTIVITY_REWARD', value: '活动奖励' },
  { key: 'ITEMLOG_REVIVE', value: '复活' },
  { key: 'ITEMLOG_GM', value: 'GM工具' },
  { key: 'ITEMLOG_OPEN_DOODAD', value: '打开doodad' },
  { key: 'ITEMLOG_REAL_MONEY_SHOP', value: '商城' },
  { key: 'ITEMLOG_TEAM_AUCTION', value: '组队拍卖' },
  { key: 'ITEMLOG_TEAM_AUCTION_FAILED', value: '组队拍卖失败' },
  { key: 'ITEMLOG_QUEST_RECYCLE', value: '环任务' },
  { key: 'ITEMLOG_EXCHANGE', value: '交易行' },
  { key: 'ITEMLOG_ARENA_COMMON_REWARD', value: '竞技场奖励' },
  { key: 'ITEMLOG_SABAC_AWARD', value: '沙巴克奖励' },
  { key: 'ITEMLOG_REPUTATION_AWARD', value: '声望奖励' },
  { key: 'ITEMLOG_SPLIT', value: '物品拆分' },
  { key: 'ITEMLOG_MOVE', value: '物品堆叠' },
  { key: 'ITEMLOG_ORGANIZE_BAG', value: '物品整理' },
  { key: 'ITEMLOG_EQUIP_LEVELUP', value: '装备升级' },
  { key: 'ITEMLOG_EQUIP_LEVELUP_FAILED', value: '装备升级失败' },
  { key: 'ITEMLOG_EQUIP_LEVELUP_SUCCEEDED', value: '装备升级成功' },
  { key: 'ITEMLOG_RECOVER_USED_UP', value: '恢复类道具用尽' },
  { key: 'ITEMLOG_MINE', value: '挖矿' },
  { key: 'ITEMLOG_ENROLL_SABAC', value: '沙巴克报名' },
  { key: 'ITEMLOG_DEATH', value: '死亡' },
  { key: 'ITEMLOG_SPELL', value: '技能效果' },
  { key: 'ITEMLOG_ATTACK', value: '攻击' },
  { key: 'ITEMLOG_ATTACKED', value: '被攻击' },
  { key: 'ITEMLOG_TRUMPET', value: '喇叭' },
  { key: 'ITEMLOG_CHECKIN_AWARD', value: '签到奖励' },
  { key: 'ITEMLOG_AWARD', value: '平台奖励' },
  { key: 'ITEMLOG_BLACK_MARKET', value: '黑市' },
  { key: 'ITEMLOG_MATERIAL', value: '矿石洗练' },
  { key: 'ITEMLOG_GAMBLE', value: '装备重铸' },
  { key: 'ITEMLOG_PACKAGE', value: '礼包' },
  { key: 'ITEMLOG_IDENTIFY', value: '物品鉴定' },
  { key: 'ITEMLOG_RANDOMIZE', value: ' 物品洗练' },
  { key: 'ITEMLOG_LUCK_OIL', value: ' 祝福油' },
  { key: 'ITEMLOG_SIGN', value: ' 装备签名' }
]
